/**
 * Single source of truth: user-defined list slugs cannot match these (first URL segment).
 * Add entries when new top-level routes are introduced.
 */
const RESERVED_LIST_SLUGS = [
  // Product (current)
  "all",
  "today",
  "todo",
  "notes",
  "note",
  // Auth
  "login",
  "signup",
  "auth",
  "callback",
  "logout",
  "register",
  "sign-out",
  "sign-in",
  "forgot-password",
  "reset-password",
  "verify-email",
  "verify",
  "oauth",
  "invite",
  "sso",
  "account",
  "security",
  "sessions",
  "devices",
  // App (likely)
  "settings",
  "preferences",
  "profile",
  "billing",
  "subscription",
  "team",
  "teams",
  "workspace",
  "workspaces",
  "dashboard",
  "inbox",
  "calendar",
  "search",
  "notifications",
  "archive",
  "trash",
  "deleted",
  "drafts",
  "shared",
  "onboarding",
  "welcome",
  "help",
  "support",
  "feedback",
  "integrations",
  "api-keys",
  "export",
  "import",
  // Admin / technical
  "admin",
  "moderation",
  "api",
  "mcp",
  "webhooks",
  "docs",
  "developer",
  "status",
  "health",
  "metrics",
  "internal",
  // Marketing / legal
  "about",
  "pricing",
  "contact",
  "blog",
  "changelog",
  "careers",
  "press",
  "legal",
  "privacy",
  "terms",
  "cookies",
  "refund",
  "gdpr",
  "security-policy",
  // i18n prefixes
  "en",
  "tr",
  "de",
  "fr",
  "es",
  "ja",
  "ko",
  "zh",
  "pt",
  "it",
  "nl",
  "pl",
  "sv",
  "da",
  "no",
  "fi",
  // Static / infra names
  "next",
  "static",
  "public",
  "assets",
  "favicon",
  "robots",
  "sitemap",
  "manifest",
  "sw",
  "offline",
  "well-known",
  "apple-touch-icon",
  "icon",
  "opengraph-image",
  "twitter-image",
] as const;

const RESERVED_LIST_SLUG_SET: ReadonlySet<string> = new Set(RESERVED_LIST_SLUGS);

export function isReservedListSlug(slug: string): boolean {
  return RESERVED_LIST_SLUG_SET.has(slug.toLowerCase());
}
